### ISSUE TITLE
Integrate GitHub with Heroku

### ISSUE THREAD

**Issue by emiovska** [emiovska/microservices-monitoring#21]

**Comment by RisteJovanoski** [comment]
I was unable to find a way to deploy the integration module as it is (whit this project structure) because Heroku requires a separate repository for every application that need to be deployed so i made a separate repository for every project from the integration module. This way the deployment to Heroku was successful. The links to the deployed applications can be found in the comments in this [issue](https://github.com/emiovska/microservices-monitoring/issues/40). Here are the links to the seperate repositories for every project of the integration module:

- [Microservice pool](https://github.com/RisteJovanoski/microservice-pool)
- [Microservice A](https://github.com/RisteJovanoski/microservice-a)
- [Microservice B](https://github.com/RisteJovanoski/microservice-b)
- [Microservice C](https://github.com/RisteJovanoski/microservice-c)
