### ISSUE TITLE
Deploy the integration module to Heroku

### ISSUE THREAD

**Issue by emiovska** [emiovska/microservices-monitoring#40]
### **Card** 
The four created project as part of the integration should be deployed on Heroku.
Each of the application should be deployed separately. 

### **Acceptance criteria**
The Microservice A/B/C are successfully registered to Microservice Pool application.
The Microservice Pool application REST API returns the active instances

**Comment by RisteJovanoski** [comment]
Deployed microservices to heroku:
MicroserviceA - https://guarded-cove-86414.herokuapp.com/healthcheck
MicroserviceB - https://mysterious-tundra-40078.herokuapp.com/check
MicroserviceC - https://infinite-forest-49940.herokuapp.com/app-check
Microservice Pool - https://vast-refuge-99698.herokuapp.com/swagger

_**Note:**_ If the microservice pool is not accessed for a while the database connection is reset and  because of that sometimes the first request may fail, but  the next requests will be successful.
